// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WalletProviderWrapper } from "@/components/WalletProviderWrapper";
import { AppKit } from "@/context/appkit";
import Navbar from "@/components/common/navbar";
import Footer from "@/components/common/Footer";
import { Toaster } from "sonner";
import AppKitThemeCustomizer from "@/components/AppKitThemeCustomizer";
import ProrectedRoute from "@/components/ProtectedRoute";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletProviderWrapper>
          <AppKit>
            {/* 👇 Mount the theme customizer globally */}
            <AppKitThemeCustomizer />

            <Navbar />
            <main className="flex-grow min-h-[calc(100vh-200px)]">
              <ProrectedRoute>
                {children}
              </ProrectedRoute>
            </main>
            <Footer />
            <Toaster richColors />
          </AppKit>
        </WalletProviderWrapper>
      </body>
    </html>
  );
}
