name: Build and Push Docker image to GHCR

on:
  push:
    branches:
      - main  # adjust if using a different branch

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/abhishekk24/stories-monorepo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_PROJECT_ID=${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
            NEXT_PUBLIC_HELIUS_API_KEY=${{ secrets.NEXT_PUBLIC_HELIUS_API_KEY }}
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} 
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:         
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          key:  ${{ secrets.REMOTE_SERVER_KEY }}
          port: ${{ secrets.SSH_PORT }} 
          script: |
            docker stop stories-app 
            docker rm stories-app 
            docker image rm ghcr.io/abhishekk24/stories-monorepo:latest
            docker pull ghcr.io/abhishekk24/stories-monorepo:latest
            docker run -d --name stories-app -p 3002:3000 -e NEXT_PUBLIC_PROJECT_ID=93d9e09393715c560c91c5d16b30a7d9 -e NEXT_PUBLIC_HELIUS_API_KEY=79fb27ad-f384-4edd-8eb0-4524558c5392 ghcr.io/abhishekk24/stories-monorepo:latest
